# Generated by Django 2.0 on 2017-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(upload_to='', verbose_name='Foto Colaborador')),
                ('ativo', models.BooleanField(default=False, verbose_name='Exibir este colaborador?')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo do Site')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço da Empresa')),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=False, verbose_name='Esta configuração esta ativa?')),
                ('area_de_servicos', models.BooleanField(default=False, verbose_name='Exibir area de servicos?')),
                ('area_de_sobrenos', models.BooleanField(default=False, verbose_name='Exibir area sobre nós?')),
                ('area_de_apresentacao', models.BooleanField(default=False, verbose_name='Exibir area de apresentacao?')),
                ('area_de_colaboradores', models.BooleanField(default=False, verbose_name='Exibir area com equipe?')),
                ('area_de_contatos', models.BooleanField(default=False, verbose_name='Exibir area para contatos?')),
            ],
            options={
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('visualizado', models.BooleanField(default=False, verbose_name='Contato ja efetuado')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='', verbose_name='Imagem do Servico')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(upload_to='')),
                ('ativo', models.BooleanField(default=False, verbose_name='Exibir este serviço?')),
            ],
        ),
    ]
