# Generated by Django 2.0 on 2017-12-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acontecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(upload_to='')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('colaboradores', models.ManyToManyField(to='administracao.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('servicos', models.ManyToManyField(to='administracao.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoSobreNos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('acontecimentos', models.ManyToManyField(to='administracao.Acontecimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracaogeral',
            name='sobre_nos',
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_apresentacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_colaboradores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_contatos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_servicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_sobrenos',
            field=models.BooleanField(default=False),
        ),
    ]
