# Generated by Django 2.0 on 2017-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_colaboradores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_contatos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='area_de_servicos',
            field=models.BooleanField(default=False),
        ),
    ]
